title: "Pegase LCA"
description: "Blog sur l’investissement de holding (immobilier, optimisation, fiscalité)"
theme: minima

# Apparence du thème
minima:
  skin: auto

# Afficher un logo dans l’en-tête
logo: /posts/_posts/pegase_logo.png

# Plugins SEO et flux
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Contrôler le menu du haut
header_pages:
  - index.md
  - categories.md
  - about.md

author:
  name: "Pegase LCA"
  avatar: /posts/_posts/pegase_logo.png

social_links:
  - { platform: github, user_url: "https://github.com/Mehdipegase" }

markdown: kramdown
permalink: pretty
